all:
	gcc -o demo demo.c
	gcc -o ptrace_exec ptrace_exec.c
	gcc -o ptrace_get_params ptrace_get_params.c
	gcc -o ptrace_modify_params ptrace_modify_params.c
	gcc -o ptrace_attach_process ptrace_attach_process.c
clean:
	rm -rf ./demo
	rm -rf ./ptrace_exec
	rm -rf ./ptrace_get_params
	rm -rf ./ptrace_modify_params
	rm -rf ./ptrace_attach_process
